package com.softschool.backend.model;

import jakarta.persistence.*;
import lombok.Data;

import java.time.Instant;

/**
 * One chat message in a teacher conversation.
 *
 * A conversation ("thread") belongs to one teacher (staffId) and one channel:
 *   channel "admin" -> teacher <-> school admin / principal
 *   channel "class" -> teacher <-> the parents of className
 *
 * senderType: TEACHER | ADMIN | PARENT. PARENT is reserved for the parent
 * portal that will be linked later: it will post into the same "class"
 * thread, and the teacher portal already shows those messages.
 *
 * clientId is generated by the portal for each outgoing message so a retry
 * after a dropped connection never creates a duplicate.
 */
@Entity
@Data
@Table(name = "teacher_message",
       uniqueConstraints = @UniqueConstraint(columnNames = {"schoolId", "staffId", "clientId"}),
       indexes = @Index(name = "idx_tmsg_thread", columnList = "schoolId,staffId,createdAt"))
public class Message {

    public static final String CH_ADMIN = "admin";
    public static final String CH_CLASS = "class";
    public static final String FROM_TEACHER = "TEACHER";
    public static final String FROM_ADMIN = "ADMIN";
    public static final String FROM_PARENT = "PARENT";

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String schoolId;

    /** The teacher this conversation belongs to. */
    @Column(nullable = false, length = 64)
    private String staffId;

    @Column(nullable = false, length = 10)
    private String channel;

    @Column(length = 100)
    private String className;

    @Column(nullable = false, length = 10)
    private String senderType;

    @Column(length = 120)
    private String senderName;

    @Column(nullable = false, length = 1000)
    private String body;

    @Column(length = 40)
    private String clientId;

    @Column(nullable = false, updatable = false)
    private Instant createdAt = Instant.now();

    private boolean readByTeacher;
    private boolean readByAdmin;
}
